### ISSUE TITLE
Issue in WPF display calendar (year and days)

### ISSUE THREAD

**Issue by PhantomD** [HEskandari/FarsiLibrary#23] opened 2018-10-29 18:44 UTC
Hi,

Thank you for this great control.

But there is an issue in WPF control which shows Gregorian Days in the calendar view as it shows year and days incorrectly while the selected date is correct when the culture is ar-SA.

How to fix this issue please.

**Comment by HEskandari** [comment] 2022-05-16 04:14
Please provide a screenshot, or code snippet. Closing for now as the issue is old. Please re-open if still relevant.

**Closed by HEskandari** 2022-05-16 04:14 UTC
